### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by aress31** [GoogleChromeLabs/dark-mode-toggle#30]
I have followed and read your tutorial at https://web.dev/prefers-color-scheme/ with great interest. It is a really nice tutorial for newbie like me, so many thanks for that.

Also, I decided to go the lazy/easy route and simply use your component rather than implementing all the logic behind for the theme switch.

My application is based on `material web components`  - https://github.com/material-components/material-components-web-components - and style wise it does not really blend in, see the following screenshot:

![image](https://user-images.githubusercontent.com/11601622/85770979-62ea3800-b713-11ea-86e2-8872cd0db94d.png)

As you can see my `language` button got a ripple around it, it is in fact a button when your component is just an icon, you can also see that the size is different, I have tried to see if I could wrap your component around a `mwc-icon-button` but I did not manage to get it to work.

This is the code that I have so far:
```
    <mwc-top-app-bar-fixed
            @MDCTopAppBar:nav=${() => (this.drawer.open = !this.drawer.open)}
          >
            <mwc-icon-button
              slot="navigationIcon"
              icon="menu"
              id="hamburger"
            ></mwc-icon-button>
            <h3 slot="title">Evil Corp</h3>
            <mwc-icon-button
              slot="actionItems"
              icon="languages"
            ></mwc-icon-button>
            <dark-mode-toggle
              slot="actionItems"
              appearance="toggle"
              permanent
            ></dark-mode-toggle>
            <!-- <mwc-icon-button-toggle
              onIcon="nights_stay"
              offIcon="wb_sunny"
              slot="actionItems"
            ></mwc-icon-button-toggle> -->
            <div class="navbar">
              <nav class="flex-container">
                <my-menu class="navbar-nav"></my-menu>
              </nav>
              <mwc-linear-progress></mwc-linear-progress>
            </div>
      </mwc-top-app-bar-fixed>
```

Also,I have notice that when my preferred theme is dark and I set the component to remember the choice when I visit the page again - refresh the page - it transition from dark theme to white theme, is this a know issue?

**Comment by tomayac** [comment]
The latest release has added CSS ::part() styling, this should allow you to fully match the look of Material. 

Regarding the flashing of the wrong theme, do you use a `dark` class or the two CSS files approach (see README)? The two CSS files approach usually has less of this undesirable effect, but in the end you have to accept that you are “fighting” the browser default by overriding the theme. 

Hope this helps, closing the Issue since it’s not really about a defect or feature request, but feel free to comment again with further questions.

**Comment by aress31** [comment]
@tomayac I am using the recommended approach - the two different `CSS files` and there is still some unwanted style flashing on refresh when remembering the non-preffered theme but as you said might be just a side effect we have to accept.

On a side note, it might be worth expanding your post on how to support more than 2 themes using this approach that could help a lot of people - including myself 😅.

Regarding the ::parts and MWC support I am not going to lie I am a newbie in web dev and web component in general so if you could provide - maybe in the README - the code on how to achieve MWC style - since Material design is one of the most used UI lib - I think it might help a lot of people out there. 

Anyway thanks again for the quality tutorial and this component it really helps quickly getting started with dark theme support.

**Comment by tomayac** [comment]
> @tomayac I am using the recommended approach - the two different `CSS files` and there is still some unwanted style flashing on refresh when remembering the non-preffered theme but as you said might be just a side effect we have to accept.

I fear so, yes. Technically, you could not display anything until the toggle's script has run and figured out the mode, but this would be even more suboptimal. As a general hint, make sure the toggle script runs as soon as possible. For example, I [preload the script](https://github.com/tomayac/blogccasion/blob/698cb4c8a9c27421d0421a6b8ce1a7b985985e26/_includes/layouts/base.njk#L14) early on during the loading of my blog.  

> On a side note, it might be worth expanding your post on how to support more than 2 themes using this approach that could help a lot of people - including myself 😅.

Right now the toggle only supports two themes. Adding support for more is currently not a planned feature, since `prefers-color-scheme` itself only supports `light` or `dark`. 

> Regarding the ::parts and MWC support I am not going to lie I am a newbie in web dev and web component in general so if you could provide - maybe in the README - the code on how to achieve MWC style - since Material design is one of the most used UI lib - I think it might help a lot of people out there.

There's a neat intro on this new kind of styling over on [CSS Tricks](https://css-tricks.com/styling-in-the-shadow-dom-with-css-shadow-parts/#styling-shadow-dom-with-part).

The exposed parts are [in the code](https://github.com/GoogleChromeLabs/dark-mode-toggle/blob/00a2dbfd8c3942304af9febd0fce9aff5fab447a/src/template-contents.tpl#L156-L170).

> Anyway thanks again for the quality tutorial and this component it really helps quickly getting started with dark theme support.

You're welcome! If you want, I'd be curious to have a look at your page now :-)

**Comment by aress31** [comment]
Thanks for the answer, I don't think that I can preload the script since I am importing it directly in my project with NPM and using it in my custom component. 🤔

A shame for the multi theme support...

Would gladly show you but it's still running locally only. 😇
