### ISSUE TITLE
Apart from `light` and `dark`, add a `system` option

### ISSUE THREAD

**Issue by filiptronicek** [GoogleChromeLabs/dark-mode-toggle#46]
Is there any way (currently) or are there any plans on adding a system theme option that would just reflect the system and not override it? Or do I have to somehow make a custom one that clears the localStorage?

**Comment by tomayac** [comment]
If you never touch the toggle, it uses what the system says.

**Comment by filiptronicek** [comment]
@tomayac yes, I'm aware of that, but if I (as a random user) once accidentally touch the toggle, I can never go back (I have no idea how to clear local storage). Is that supposed to work like that? I think there could be a better solution.

**Comment by tomayac** [comment]
If the toggle doesn't have the [`permanent` attribute](https://github.com/GoogleChromeLabs/dark-mode-toggle#properties), the site will reset to the system default.

Let's assume the system preference is light mode.

`<dark-mode-toggle>`:

- Toggle dark mode. 
- Reload.
- Mode is light again.

`<dark-mode-toggle permanent>`:

- Toggle dark mode. 
- Reload.
- Mode is dark again.

**Comment by tomayac** [comment]
(It's up to the site owner to choose if they set the `permanent` attribute. Personally, I do on my [blog](https://blog.tomayac.com/).)

**Comment by vapier** [comment]
this is just bad UX.  interacting with UI that cannot be undone, and practically speaking, is not recoverable for users, is bad design.  a pretty fundamental key UI principle is that actions be easy reversible which this violates.

it's not like Google doesn't know how to write this behavior.  some of its properties have a tristate theme selector.

**Comment by tomayac** [comment]
I changed my mind and now do think we should have at least an option to have a three-way toggle. Is anyone on this thread happy to work on a PR that adds such a feature?

**Comment by tomayac** [comment]
Functionality-wise, the "system" option would just need to delete the localStorage entry. The actual work would more need to focus on how to expose this UI wise. Some of the [properties](https://github.com/GoogleChromeLabs/dark-mode-toggle?tab=readme-ov-file#properties) need rethinking, and the HTML structure, too. The appearance `toggle` means there's just one visible thing to click at a time that cycles through the possible states, and the `switch` means all possible states are visible at the same time and clickable.

**Comment by vapier** [comment]
for me, the most time consuming part is the graphics, not the underlying logic.  do we have an icon ready-to-go here ?

**Comment by tomayac** [comment]
I have seen sites use a slash icon like [this](https://user-images.githubusercontent.com/56068232/211295175-e9f2cafe-5725-4e2c-903a-d4914580f030.jpg).

**Comment by Haocen** [comment]
I have implemented a new appearance `three-way` here:
https://dark-mode-toggle.pages.dev/

Not sure if it is what you have in mind.
The slider thumb only reflects remembered color scheme, otherwise it stays in the middle.
The overall look and feel of `three-way` still changes as the color scheme is toggled even if it is not remembered(permanent), either via `prefers-color-scheme` or another `dark-mode-toggle`.

https://github.com/user-attachments/assets/109d897d-58e5-442a-9404-28763f0223bd

`three-way` is composed of 3 radio input with its labels and icons engineered to be pixel perfect such that it scales accordingly to `--dark-mode-toggle-icon-size` css variable.

**Comment by tomayac** [comment]
@Haocen This looks really beautiful. Are you in a position to add a baseline demo (that is, as in the screenshot below, with an additional option) that adds a "System" option without fancy animations, just boiled down to the minimum?
  
![Screenshot 2024-09-17 at 10 58 52](https://github.com/user-attachments/assets/98225863-1f14-4063-bcf1-a107fcc62fdb)

I think if we have this and you made a PR, it would fix this issue.

**Comment by Haocen** [comment]
I've added one [here](https://dark-mode-toggle.pages.dev/).
![image](https://github.com/user-attachments/assets/3c7648a8-6b9c-4c02-841a-9d22ec6b7874)

I tried to setup end to end test coverage and it seems it is not working as expected in Webkit. Blink and Gecko seems fine.
I'm not immediately able to figure out why, but it could have something to do with `:has()` although [caniuse indicated I should be fine](https://caniuse.com/?search=has).

I'll keep looking into it.

**Comment by tomayac** [comment]
I tried it in Safari Version 18.1 (20619.2.1) that ships as part of macOS Sequoia 15.1 Beta (24B5035e) and it worked as expected. Maybe you're on an earlier version still?

**Comment by Haocen** [comment]
@tomayac can you help with the forensic study:
https://bugtrace.pages.dev/

I included iOS 17, iOS 18 and macOS Sequoia as well as macOS Ventura in the test suite they all consistently showing the following problems:
- 1px gap due to rounding float point value of the width of the labels.
- When switch from permenant light/dark to system color scheme the position of the thumb is not rendered properly(although the css `position` is updated as expected).

Appreciate your insights.

-- Update --
Funny the thumb position bug goes away if there is another appearance of `dark-mode-toggle` being used on the same page, I guess this is why the demo page is bug free.

-- Update 2 --
Could be related to [this bug in webkit](https://bugs.webkit.org/show_bug.cgi?id=234556#c16).

**Comment by tomayac** [comment]
I'm not sure what's the code difference between https://bugtrace.pages.dev/ and https://dark-mode-toggle.pages.dev/, but the latter works just fine for me in Safari, whereas the former sometimes gets stuck somehow and there's no way to switch back to a previous setting for a while.

**Comment by Haocen** [comment]
They are the same, I've added sub resource integrity to both pages and they should match each other.

Seems to be a Webkit bug to me.

**Comment by tomayac** [comment]
I agree that this looks like a bug. If you manage to isolate it, maybe worth filing one at https://bugs.webkit.org/.

If you want to open a PR to this repo with your changes, I'd be happy to merge it.
