### ISSUE TITLE
dark-mode-toggle with React

### ISSUE THREAD

**Issue by herablog** [GoogleChromeLabs/dark-mode-toggle#64]
Hi,

A DOMException error occurs when `<dark-mode-toggle>` is used in React apps. 

> Failed to construct 'CustomElement': The result must not have attributes

I think it occurs when [document.createElement](https://github.com/facebook/react/blob/2c7dea73659da283fa433f5fd657a5a29797fd67/packages/react-dom/src/client/ReactDOMComponent.js#L429) has been called.

The error would be solved if the DOM related tasks move from `constructor` to `connectedCallback`, but I am not sure this is an appropriate change for dark-mode-toggle.

**Comment by tomayac** [comment]
Thanks for reporting this. Would you maybe have a minimal reproduction case for me to look at?

**Comment by herablog** [comment]
Thanks for you reply. You can see the error at https://ameba-spindle-website--pr64-feat-theme-switch-b938v5b1.web.app/

https://user-images.githubusercontent.com/869023/181470862-bd47b5ce-21aa-4632-befb-966e6d96d239.mp4

**Comment by tomayac** [comment]
Version `0.11.0` fixes this. Thanks for reporting again!

**Comment by herablog** [comment]
The site has no error. Thanks a lot for your work!

**Comment by tomayac** [comment]
Turns out the release broke other things in subtle ways. The HTML spec actually [says](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance):

_"In general, the constructor should be used to set up initial state and default values, and to set up event listeners and possibly a [shadow root](https://dom.spec.whatwg.org/#concept-shadow-root)."_

React is [known](https://custom-elements-everywhere.com/libraries/react/results/results.html) to behave badly with custom elements. Please try using the element outside of React. Here's an [example](https://codesandbox.io/s/hungry-browser-ywgfrh?file=/public/index.html) where I show this.

**Comment by tomayac** [comment]
(Please update to version `0.12.0`.)

**Comment by tomayac** [comment]
I think version `0.13.0` now works natively with React. I managed to shuffle the DOM work around, so the shadow DOM gets created in the `constructor`, but attribute work happens in the `connectedCallback`.

**Comment by herablog** [comment]
> I think version `0.13.0` now works natively with React. I managed to shuffle the DOM work around, so the shadow DOM gets created in the `constructor`, but attribute work happens in the `connectedCallback`.

Yes, it seems the perfect change. I should have said "attribute work" instead of "DOM related tasks", sorry for that. Thanks for your great work again!

**Comment by tomayac** [comment]
Thanks for filing this issue, I have learned a lot from it and am currently documenting my learnings in a blog post.

**Comment by herablog** [comment]
Yeah, I have also learned about Custom Elements. Our team is planning to extend dark-mode-toggle, and to use it in our website. I'm looking forward to reading your blog post. Thank you.
